# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-17 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("energy", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="message",
            name="img",
            field=models.FileField(default="", upload_to=b""),
        )
    ]
