# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("energy", "0002_message_img")]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="pub_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        )
    ]
