# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0007_commit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.Type'),
        ),
    ]
