# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("energy", "0008_auto_20180321_0820")]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_deal",
            field=models.BooleanField(default=False),
        )
    ]
