# Generated by Django 2.1.4 on 2019-01-19 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0010_auto_20180324_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='energy.Type'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articleimg',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='energy.Article'),
        ),
        migrations.AlterField(
            model_name='articleimg',
            name='img',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='commit',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='energy.Message'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='energy.Type'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
